version: '3'

services:

  redis:
    image: redis
    container_name: "redis"
  queue:
    image: rabbitmq
    container_name: "queue"
  app:
    build: ./code-editor
    ports:
      - 3000:3000
    volumes:
      - ./code-editor:/usr/home/app/
  worker:
    build: ./queue
    restart: always
    depends_on:
      queue:
        condition: service_started
        
  

    